title: Ariel Lu
logo: "/images/Ariel.JPEG?raw=true" # your photo (or logo) here
description: >
  Supply Chain Analyst
  <br>
  <br>
  <a href="https://www.linkedin.com/in/larrychencpa/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
