title: Ariel Lu
logo: "/images/Ariel new.JPEG?raw=true" # your photo (or logo) here
description: >
  <br>
  Passionate about supply chain management and ERP implementation, driving efficiency and digital transformation in business operations.
  <br><br>
  <a href="https://www.linkedin.com/in/pin-ying-lu">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
