title: Ariel Lu
logo: "/images/Ariel new.JPEG?raw=true" # your photo (or logo) here
description: >
  5+ years professional experience in supply chain
  <br>
  <br>
  <a href="https://www.linkedin.com/in/pin-ying-lu">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
